In [ ]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

In [ ]:
current_dir = Path.cwd().parent

In [ ]:
df_swiss_train = pd.read_json(str(current_dir / "datasets/SwissProt_2021_04/SwissProt_2021_04_train.json"))
df_swiss_train

       id_uniprot                                           sequence ec_number
0          P0C9F0  MVRLFYNPIKYLFYRRSCKKRLRKALKKLNFYHPPKECCQIYRLLE...   0.0.0.0
1          P0C9F1  MVRLFHNPIKCLFYRGSRKTREKKLRKSLKKLNFYHPPGDCCQIYR...   0.0.0.0
2          P0C9F2  MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...   0.0.0.0
3          P0C9E9  MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...   0.0.0.0
4          Q65209  MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKKLK...   0.0.0.0
...           ...                                                ...       ...
561204     Q6UY62  MGNSKSKSKLSANQYEQQTVNSTKQVAILKRQAEPSLYGRHNCRCC...   0.0.0.0
561205     P08105  MSSSLEITSFYSFIWTPHIGPLLFGIGLWFSMFKEPSHFCPCQHPH...   0.0.0.0
561206     Q88470  MGNCNRTQKPSSSSNNLEKPPQAAEFRRTAEPSLYGRYNCKCCWFA...   0.0.0.0
561207     A9JR22  MGLRYSKEVRDRHGDKDPEGRIPITQTMPQTLYGRYNCKSCWFANK...   0.0.0.0
561208     B2ZDY1  MGLRYSKDVKDRYGDREPEGRIPITLNMPQSLYGRYNCKSCWFANK...   0.0.0.0

[522964 rows x 3 columns]

In [ ]:
df_swiss_test = pd.read_json(str(current_dir / "datasets/SwissProt_2021_04/SwissProt_2021_04_test.json"))
df_swiss_test

,id_uniprot,sequence,ec_number
238444,Q0UG93,MAGGKGKTGGKTGGKGDSHVKTTKSHSAKAGLQFPCGRIKRHLRTI...,0.0.0.0
66527,B7MXI6,MPRANEIKKGMVLNYNGKLLLVKDIDIQSPTARGAATLYKMRFSDV...,0.0.0.0
384133,Q31XA7,MIEFDNLTYLHGKPQGTGLLKANPEDFVVVEDLGFEPDGEGEHILV...,5.4.99.27
80414,B2SYX4,MKHIVKHIHFVGIGGVGMSGIAEVLVNLGYQVSGSDLTSNAITDRL...,6.3.2.8
549535,B4PL32,MVRTKNQSSSSSASSSSTKSPIKSSSATGSSGGGVGGRQSTHRSSS...,5.6.1.1
...,...,...,...
446139,P47181,MNTDSHNLSEPYNIGGQKYINMKKKEDLGVCQPGLTQKAFTVEDKF...,0.0.0.0
365835,A2XWN6,METEGWPALQPLLCLAWIATTLPIIVAALPIPAAAGGHLLRRLLSA...,1.3.1.94
194047,A5D9Y9,MSFNIPNPSLLGIFLVISTHSGPTSVFSYPPELSSDKTSSQRRNRH...,0.0.0.0
313289,C6DCQ0,MSNQLSPKPPVNPIVMGKIGSAYGIRGWLRVFSSTEDAESIFDYQP...,0.0.0.0
345665,P9WNC0,MPEGDTVWHTAATLRRHLAGRTLTRCDIRVPRFAAVDLTGEVVDEV...,0.0.0.0

In [ ]:
df_swiss_val = pd.read_json(str(current_dir / "datasets/SwissProt_2021_04/SwissProt_2021_04_valid.json"))
df_swiss_val

,id_uniprot,sequence,ec_number
34088,Q5RCW6,MEVRASLQKVSGSSDSVATMNSEEFVLVPQYADDNSTKHEEKPQLK...,0.0.0.0
302495,Q8IQF1,MRLLARHAIRLLGQENSAGEVASLSRGAIRLKATTGYLNLATASVQ...,0.0.0.0
276346,O34560,MLPELQRSITWIQGTALTIGAVLGCGILILPSVTADTAGPASLFVW...,0.0.0.0
164209,Q24VA6,MAGQNRNKDFLIVSKDILPEAILKTAQAKELLVKGDANTINEAVDR...,0.0.0.0
348587,P48596,MSFTRQLSEMSASELNDAIDDTNFPQAHILSRGRNNSVCSTSSTSG...,3.5.4.16
...,...,...,...
446654,Q5UPK6,MQSSKNKINGPINLVRIEGVIDGINKVVYLFMDYHADINEQTNCED...,0.0.0.0
519381,C3K4H5,MNALTLPDIAAQASRQALPLDWVGMCGIALPILIDGQRLTATADAG...,3.5.4.16
300385,P77257,MQTSDTRALPLLCARSVYKQYSGVNVLKGIDFTLHQGEVHALLGGN...,7.6.2.13
326729,Q7TUP1,MFPNSKVELPKSTPVRRIGLSVQYEGSNFCGWQRQPQAVSVQQVLE...,5.4.99.12
202672,Q3IJK4,MHLNTLSPAAGSKTAPKRVGRGIGSGLGKTGGRGHKGQKSRSGGKV...,0.0.0.0

In [ ]:
df_18 = pd.read_csv(str(current_dir / 'datasets/GH18.csv'))
df_19 = pd.read_csv(str(current_dir / 'datasets/GH19.csv'))

In [ ]:
df_18["Familia"] = "GH18"
df_18

             Nombre                                          Secuencia Familia
0        AAB97779.1  MRKFNKPLLALLIGSTLCSAAQAAAPGKPTIAWGNTKFAIVEVDQA...    GH18
1        AAC44673.1  EYHMGNTMTKAIYDKFKAATPYGNTVATGAVPSETVDIAVSIGGFK...    GH18
2        AAM08773.1  MVNGYLFREYIGAQFTGVRFSDVPVNPGLSFHFILAFAIDYFMATQ...    GH18
3        AAM08776.1  MTNGYLFREYIGAQFTGVRFSDVPINPNLSFNFILSFAIDYTSPAG...    GH18
4        BAB79618.1  MKQHVKTLKLSQMASILGAIFCANSYAYNCDGLPEWSQSSAYNGGA...    GH18
..              ...                                                ...     ...
361      CAQ78442.1  MKRIFINSAIASALFISYGANAFDCSSLPLWQNSEPYSGGAEIQQN...    GH18
362      CCD63028.1  MLLGKFLLVASFILPIAYTWTGATIRNHPADVVAARNKITSRSVAR...    GH18
363    KAB2598727.1  MASKTQTLALTLSLLILLSSCKSSQAAGIAIYWGQNGNEGTLADAC...    GH18
364      QGN68168.1  MSKTITYYNSGAVPLINASELPYDVVNLAFLSSSSNNPFNLVLSGA...    GH18
365  XP_018173934.1  MLRSLMQCIAALGLLQVASFVSGAAISAPVEGLVSKRASGSANGVY...    GH18

[366 rows x 3 columns]

In [ ]:
df_19["Familia"] = "GH19"
df_19

,Nombre,Secuencia,Familia
0,BAE86996.1,MLNPSKLSVLLGWAIAASSHAAMNIQPDPENPNGYVVARADITAAE...,GH19
1,AAA18586.1,MRAFVLFAVVAMAATMAVAEQCGSQAGGATCPNCLCCSRFGWCGST...,GH19
2,AAA32769.1,MPPQKENHRTLNKMKTNLFLFLIFSLLLSLSSAEQCGRQAGGALCP...,GH19
3,AAA32941.1,MRSLAVVVAVVATVAMAIGTARGSVSSIVSRAQFDRMLLHRNDGAC...,GH19
4,AAA33444.1,MANAPRILALGLLALLCAAAGPAAAQNCGCQPNFCCSKFGYCGTTD...,GH19
...,...,...,...
88,BAA03751.1,MRALALAVVAMAVVAVRGEQCGSQAGGALCPNCLCCSQYGWCGSTS...,GH19
89,CAB01591.1,MVYCTASLPLLLLLLVGLLAGEAFAEQCGRQAGGALCPGGLCCSQF...,GH19
90,CAC17793.1,MRLREFTALSSLLFSLLLLSASAEQCGSQAGGARCASGLCCSKFGW...,GH19
91,sp|P27054|CHI4_PHAVU,MGNKLVLVLVAVALVMGPKNVSAQNCGCAEGLCCSQYGYCGTGEDY...,GH19
92,sp|P85084|CHIT_CARPA,GIEKIISRSMFDQMLKHRNNPACPAKGFYTYDAFLAAAKSFPSFGT...,GH19

In [ ]:
# Unir los DataFrames
df_combined = pd.concat([df_18, df_19], ignore_index=True)

df_combined

,Nombre,Secuencia,Familia
0,AAB97779.1,MRKFNKPLLALLIGSTLCSAAQAAAPGKPTIAWGNTKFAIVEVDQA...,GH18
1,AAC44673.1,EYHMGNTMTKAIYDKFKAATPYGNTVATGAVPSETVDIAVSIGGFK...,GH18
2,AAM08773.1,MVNGYLFREYIGAQFTGVRFSDVPVNPGLSFHFILAFAIDYFMATQ...,GH18
3,AAM08776.1,MTNGYLFREYIGAQFTGVRFSDVPINPNLSFNFILSFAIDYTSPAG...,GH18
4,BAB79618.1,MKQHVKTLKLSQMASILGAIFCANSYAYNCDGLPEWSQSSAYNGGA...,GH18
...,...,...,...
454,BAA03751.1,MRALALAVVAMAVVAVRGEQCGSQAGGALCPNCLCCSQYGWCGSTS...,GH19
455,CAB01591.1,MVYCTASLPLLLLLLVGLLAGEAFAEQCGRQAGGALCPGGLCCSQF...,GH19
456,CAC17793.1,MRLREFTALSSLLFSLLLLSASAEQCGSQAGGARCASGLCCSKFGW...,GH19
457,sp|P27054|CHI4_PHAVU,MGNKLVLVLVAVALVMGPKNVSAQNCGCAEGLCCSQYGYCGTGEDY...,GH19
458,sp|P85084|CHIT_CARPA,GIEKIISRSMFDQMLKHRNNPACPAKGFYTYDAFLAAAKSFPSFGT...,GH19

In [ ]:
df_swiss_all = pd.concat([df_swiss_train, df_swiss_test, df_swiss_val], ignore_index=True)
df_swiss_all

,id_uniprot,sequence,ec_number
0,P0C9F0,MVRLFYNPIKYLFYRRSCKKRLRKALKKLNFYHPPKECCQIYRLLE...,0.0.0.0
1,P0C9F1,MVRLFHNPIKCLFYRGSRKTREKKLRKSLKKLNFYHPPGDCCQIYR...,0.0.0.0
2,P0C9F2,MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...,0.0.0.0
3,P0C9E9,MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...,0.0.0.0
4,Q65209,MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKKLK...,0.0.0.0
...,...,...,...
523986,Q5UPK6,MQSSKNKINGPINLVRIEGVIDGINKVVYLFMDYHADINEQTNCED...,0.0.0.0
523987,C3K4H5,MNALTLPDIAAQASRQALPLDWVGMCGIALPILIDGQRLTATADAG...,3.5.4.16
523988,P77257,MQTSDTRALPLLCARSVYKQYSGVNVLKGIDFTLHQGEVHALLGGN...,7.6.2.13
523989,Q7TUP1,MFPNSKVELPKSTPVRRIGLSVQYEGSNFCGWQRQPQAVSVQQVLE...,5.4.99.12
523990,Q3IJK4,MHLNTLSPAAGSKTAPKRVGRGIGSGLGKTGGRGHKGQKSRSGGKV...,0.0.0.0

In [ ]:
len(df_swiss_all["sequence"].values)

523991

In [ ]:
len(set(df_swiss_all["sequence"].values))

440925

In [ ]:
# Buscar filas donde la columna 'sequence' se repita
duplicados = df_swiss_all[df_swiss_all.duplicated(subset=['sequence'], keep=False)]
duplicados

,id_uniprot,sequence,ec_number
2,P0C9F2,MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...,0.0.0.0
3,P0C9E9,MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...,0.0.0.0
21,P0C9I0,MLVIFLGILGLLASQVSSQLVGQLRPTEDPPEEELEYWCAYMESCQ...,0.0.0.0
22,P0C9H7,MLVIFLGILGLLASQVSSQLVGQLRPTEDPPEEELEYWCAYMESCQ...,0.0.0.0
55,B2SAT5,MNSFRKTCAGALALIFGATSIVPTVAAPMNMDRPAINQNVIQARAH...,0.0.0.0
...,...,...,...
523986,Q5UPK6,MQSSKNKINGPINLVRIEGVIDGINKVVYLFMDYHADINEQTNCED...,0.0.0.0
523987,C3K4H5,MNALTLPDIAAQASRQALPLDWVGMCGIALPILIDGQRLTATADAG...,3.5.4.16
523988,P77257,MQTSDTRALPLLCARSVYKQYSGVNVLKGIDFTLHQGEVHALLGGN...,7.6.2.13
523989,Q7TUP1,MFPNSKVELPKSTPVRRIGLSVQYEGSNFCGWQRQPQAVSVQQVLE...,5.4.99.12
523990,Q3IJK4,MHLNTLSPAAGSKTAPKRVGRGIGSGLGKTGGRGHKGQKSRSGGKV...,0.0.0.0

In [ ]:
final = df_swiss_all.drop_duplicates(subset=['sequence'], keep='first')
final

       id_uniprot                                           sequence ec_number
0          P0C9F0  MVRLFYNPIKYLFYRRSCKKRLRKALKKLNFYHPPKECCQIYRLLE...   0.0.0.0
1          P0C9F1  MVRLFHNPIKCLFYRGSRKTREKKLRKSLKKLNFYHPPGDCCQIYR...   0.0.0.0
2          P0C9F2  MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...   0.0.0.0
4          Q65209  MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKKLK...   0.0.0.0
5          P0C9F4  MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKNLE...   0.0.0.0
...           ...                                                ...       ...
522959     Q6UY62  MGNSKSKSKLSANQYEQQTVNSTKQVAILKRQAEPSLYGRHNCRCC...   0.0.0.0
522960     P08105  MSSSLEITSFYSFIWTPHIGPLLFGIGLWFSMFKEPSHFCPCQHPH...   0.0.0.0
522961     Q88470  MGNCNRTQKPSSSSNNLEKPPQAAEFRRTAEPSLYGRYNCKCCWFA...   0.0.0.0
522962     A9JR22  MGLRYSKEVRDRHGDKDPEGRIPITQTMPQTLYGRYNCKSCWFANK...   0.0.0.0
522963     B2ZDY1  MGLRYSKDVKDRYGDREPEGRIPITLNMPQSLYGRYNCKSCWFANK...   0.0.0.0

[440925 rows x 3 columns]

In [ ]:
final["ec_number"].value_counts()

ec_number
0.0.0.0      255106
2.7.7.6        3207
2.7.11.1       2368
3.6.4.12       1852
7.1.2.2        1761
              ...
2.5.1.153         1
4.2.3.52          1
4.2.3.117         1
4.2.3.56          1
2.4.2.40          1
Name: count, Length: 4743, dtype: int64

In [ ]:
# Agregar la columna 'IsEnzime' con valores 1 si 'ec_number' es distinto de '0.0.0.0', 0 si no
final.loc[:, 'IsEnzime'] = final['ec_number'].apply(lambda x: 1 if x != '0.0.0.0' else 0)
final

,id_uniprot,sequence,ec_number,IsEnzime
0,P0C9F0,MVRLFYNPIKYLFYRRSCKKRLRKALKKLNFYHPPKECCQIYRLLE...,0.0.0.0,0
1,P0C9F1,MVRLFHNPIKCLFYRGSRKTREKKLRKSLKKLNFYHPPGDCCQIYR...,0.0.0.0,0
2,P0C9F2,MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...,0.0.0.0,0
4,Q65209,MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKKLK...,0.0.0.0,0
5,P0C9F4,MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKNLE...,0.0.0.0,0
...,...,...,...,...
522959,Q6UY62,MGNSKSKSKLSANQYEQQTVNSTKQVAILKRQAEPSLYGRHNCRCC...,0.0.0.0,0
522960,P08105,MSSSLEITSFYSFIWTPHIGPLLFGIGLWFSMFKEPSHFCPCQHPH...,0.0.0.0,0
522961,Q88470,MGNCNRTQKPSSSSNNLEKPPQAAEFRRTAEPSLYGRYNCKCCWFA...,0.0.0.0,0
522962,A9JR22,MGLRYSKEVRDRHGDKDPEGRIPITQTMPQTLYGRYNCKSCWFANK...,0.0.0.0,0
522963,B2ZDY1,MGLRYSKDVKDRYGDREPEGRIPITLNMPQSLYGRYNCKSCWFANK...,0.0.0.0,0

In [ ]:
final["IsEnzime"].value_counts()

IsEnzime
0    255106
1    185819
Name: count, dtype: int64

In [ ]:
# Dividir el DataFrame en 80% train y 20% restante (test + validación)
df_train, df_temp = train_test_split(final, test_size=0.1, stratify=final['IsEnzime'], random_state=42)

# Dividir el 10% restante en 10% test y 10% validación
df_test, df_val = train_test_split(df_temp, test_size=0.5, stratify=df_temp['IsEnzime'], random_state=42)

# Ver tamaños de los conjuntos
print(f'Tamaño del train set: {len(df_train)}')
print(f'Tamaño del test set: {len(df_test)}')
print(f'Tamaño del validation set: {len(df_val)}')

Tamaño del train set: 396832
Tamaño del test set: 22046
Tamaño del validation set: 22047

In [ ]:
# Contar cuántas instancias hay de cada clase en el conjunto de entrenamiento
train_counts = df_train['IsEnzime'].value_counts()

# Contar cuántas instancias hay de cada clase en el conjunto de prueba
test_counts = df_test['IsEnzime'].value_counts()

# Contar cuántas instancias hay de cada clase en el conjunto de validación
val_counts = df_val['IsEnzime'].value_counts()

print("Conteo en el conjunto de entrenamiento:")
print(train_counts)

print("\nConteo en el conjunto de prueba:")
print(test_counts)

print("\nConteo en el conjunto de validación:")
print(val_counts)

Conteo en el conjunto de entrenamiento:
IsEnzime
0    229595
1    167237
Name: count, dtype: int64

Conteo en el conjunto de prueba:
IsEnzime
0    12755
1     9291
Name: count, dtype: int64

Conteo en el conjunto de validación:
IsEnzime
0    12756
1     9291
Name: count, dtype: int64

In [ ]:
df_train.to_csv(str(current_dir / 'datasets/Train/train.csv'), index=False)
df_test.to_csv(str(current_dir / 'datasets/Test/test.csv'), index=False)
df_val.to_csv(str(current_dir / 'datasets/Validation/valid.csv'), index=False)