In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import time
import os

In [ ]:
current_dir = Path.cwd().parent

In [ ]:
train_dir = str(current_dir / 'datasets/Train/train.csv')
valid_dir = str(current_dir / 'datasets/Validation/valid.csv')
test_dir = str(current_dir / 'datasets/Test/test.csv')
g18_19_dir = str(current_dir / 'datasets/GH18_GH19_descriptores.csv')
emb_dir = str(current_dir / 'datasets/All_Embeddings')
valid_emb_dir = str(current_dir / 'datasets/Valid_Embeddings')
test_emb_dir = str(current_dir / 'datasets/Test_Embeddings')
g18_19_emb_dir = str(current_dir / 'datasets/G18_G19_Embeddings')

In [ ]:
info = np.load(os.path.join(emb_dir, 'info.npy'))
info[0] = 8
np.save(os.path.join(emb_dir, 'info.npy'), info)

In [16]:
df_train = pd.read_csv(train_dir)
df_train.head(5)

,id_uniprot,sequence,ec_number,IsEnzime
0,C0HLW5,TDAVANGVHAISGVVDS,0.0.0.0,0
1,Q66C72,MAQVAKKILVTCALPYANGSIHLGHMLEHIQADIWVRFQRMRGNQV...,6.1.1.10,1
2,Q3Z4P3,MATLFIADLHLCVEEPAITAGFLRFLAGEARKADALYILGDLFEAW...,3.6.1.54,1
3,Q6YDN7,MLRRKPTRLELKLDDIEEFENIRKDLEARKKQKEDVEGVGTSDGEG...,0.0.0.0,0
4,Q1JHB8,MEALKKIAGVTAAQYVTDGMTIGLGTGSTAYYFVEEIGRRVKQEGL...,5.3.1.6,1

In [ ]:
len(df_train)

396832

In [ ]:
df_valid = pd.read_csv(valid_dir)
df_valid.head(5)

,id_uniprot,sequence,ec_number,IsEnzime
0,A7NR45,MSKLKITYRKSAIGYSHDQKATIRSLGLRRLNSVVVHDDTPTIRGM...,0.0.0.0,0
1,Q5FM74,MANRNDSRNNRRNKDDIEDQLVAVNRITKVVKGGRRMRFAALVVVG...,0.0.0.0,0
2,Q68WM5,MIKKEIIILCGPTASGKSYLGHELAKAYGCEIINIDSMQVYREIPI...,2.5.1.75,1
3,Q6HJF2,MKKVDVKESAVGRETRIRKQWNEQSIFEQSIQNREGAQSFVFYEGP...,6.1.1.5,1
4,Q35438,MTNIRKTHPLMKIINSSFIDLPAPSNISAWWNFGSLLGICLILQIL...,0.0.0.0,0

In [ ]:
df_test = pd.read_csv(test_dir)
df_test.head(5)

,Unnamed: 0,id_uniprot,sequence,ec_number,IsEnzime
0,0,Q03599,MQWPLIAALFTQLYHFVIGDDCYCPLCELDKLPDNCTTIHGHIQMG...,0.0.0.0,0
1,1,P0CH32,MQIFVKTLTGKTITLEVESSDTIDNVKAKIQDKEGIPPDQQRLIFA...,0.0.0.0,0
2,2,Q41224,MMTRGATRMTRTVLGHMGPRYFSTAIFRNDAGTGVMSGAAVFMHGV...,1.10.3.11,1
3,3,Q6CUC6,MAKSPKRKNSEPEDLSSNKRSKSFEFGKVENGLEPSGSDFGSDLPT...,0.0.0.0,0
4,4,Q9TF49,MTNTRKTHPLIKIINHSFIDLPAPSNISAWWNFGSLLGLCLIIQIL...,0.0.0.0,0

In [4]:
df_g18_19 = pd.read_csv(g18_19_dir)
df_g18_19.head(5)

,Nombre,Secuencia,Familia,A,R,N,D,C,E,Q,...,_HydrophobicityD2001,_HydrophobicityD2025,_HydrophobicityD2050,_HydrophobicityD2075,_HydrophobicityD2100,_HydrophobicityD3001,_HydrophobicityD3025,_HydrophobicityD3050,_HydrophobicityD3075,_HydrophobicityD3100
0,AAB97779.1,MRKFNKPLLALLIGSTLCSAAQAAAPGKPTIAWGNTKFAIVEVDQA...,GH18,9.947,2.309,6.039,6.572,0.888,3.375,4.618,...,1.243,22.202,49.378,77.087,99.645,0.178,25.755,49.201,71.226,99.822
1,AAC44673.1,EYHMGNTMTKAIYDKFKAATPYGNTVATGAVPSETVDIAVSIGGFK...,GH18,9.639,1.205,6.627,7.831,0.000,2.410,2.410,...,1.205,19.880,49.398,72.289,99.398,2.410,25.301,48.193,74.699,97.590
2,AAM08773.1,MVNGYLFREYIGAQFTGVRFSDVPVNPGLSFHFILAFAIDYFMATQ...,GH18,13.287,3.147,4.895,5.245,0.350,3.846,3.846,...,1.399,24.126,46.853,72.727,100.000,0.350,19.930,47.902,71.678,98.951
3,AAM08776.1,MTNGYLFREYIGAQFTGVRFSDVPINPNLSFNFILSFAIDYTSPAG...,GH18,10.417,2.778,4.861,7.292,0.347,3.819,3.472,...,0.694,21.875,44.097,72.917,100.000,0.347,24.653,49.653,71.875,98.958
4,BAB79618.1,MKQHVKTLKLSQMASILGAIFCANSYAYNCDGLPEWSQSSAYNGGA...,GH18,8.582,1.639,8.100,6.654,0.868,3.761,3.954,...,0.386,25.169,49.952,76.374,99.711,0.096,24.108,50.916,74.542,100.000

In [5]:
!pip install "transformers<5"
import transformers
from transformers import BertTokenizer, TFBertModel

Collecting transformers<5
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers<5) (3.29.3)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers<5)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<5) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers<5) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers<5) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5) (2026.5.20)
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 119.5 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 48.7 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.19.0
    Uninstalling huggingface_hub-1.19.0:
      Successfully uninstalled huggingface_hub-1.19.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.12.0
    Uninstalling transformers-5.12.0:
      Successfully uninstalled transformers-5.12.0
Successfully installed huggingface-hub-0.36.2 transformers-4.57.6

In [6]:
model_name = "Rostlab/prot_bert"
tokenizer = BertTokenizer.from_pretrained(model_name, do_lower_case=False)
model = TFBertModel.from_pretrained(model_name, from_pt=True)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/86.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/81.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/361 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.68G [00:00<?, ?B/s]

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

In [ ]:
df_train['processed_sequence'] = df_train['sequence'].apply(lambda seq: " ".join(list(seq)))

In [ ]:
df_valid['processed_sequence'] = df_valid['sequence'].apply(lambda seq: " ".join(list(seq)))

In [ ]:
df_test['processed_sequence'] = df_test['sequence'].apply(lambda seq: " ".join(list(seq)))

In [7]:
df_g18_19['processed_sequence'] = df_g18_19['Secuencia'].apply(lambda seq: " ".join(list(seq)))

In [8]:
length_subsets = 40000

In [ ]:
def generate_embeddings(sequences, dir, batch_size=96):
    global length_subsets, tokenizer, model
    def generate_embeddings_numpy(sequences, batch_size):
        global tokenizer, model
        all_embeddings = []
        for i in range(0, len(sequences), batch_size):
            end = len(sequences) if i + batch_size > len(sequences) else i + batch_size
            print(f'De {i} a {end}')
            batch_seqs = sequences[i:end]
            encoded = tokenizer(
                batch_seqs.tolist(),
                padding=True,
                truncation=True,
                max_length=512,
                return_tensors="tf"
            )
            outputs = model(encoded)
            cls_embeddings = outputs.last_hidden_state[:, 0, :].numpy()
            all_embeddings.append(cls_embeddings)
        return np.vstack(all_embeddings)

    info_name = 'info.npy'
    info_dir = os.path.join(dir, info_name)
    if not os.path.exists(info_dir):
        data = np.array([0, 0])
        np.save(info_dir, data)
    data = np.load(info_dir)
    current_subset = int(data[0])
    current_time = float(data[1])
    total_subsets = len(sequences) // length_subsets if len(sequences) % length_subsets == 0 else len(sequences) // length_subsets + 1
    if current_subset == total_subsets:
        print('Embeddings already generated')
        return
    for i in range(int(current_subset), int(total_subsets)):
        print(f'Starting subset: {i} current time: {current_time}s')
        start = time.time()
        start_index = length_subsets * current_subset
        end_index = min(start_index + length_subsets, len(sequences))
        embs = generate_embeddings_numpy(sequences[start_index:end_index], batch_size)
        np.save(os.path.join(dir, f'subset_{current_subset}.npy'), embs)
        current_subset += 1
        end = time.time()
        current_time += end - start
        np.save(info_dir, np.array([current_subset, current_time]))
        print(f'Saved, current time: {current_time}s')

In [ ]:
generate_embeddings(df_train['processed_sequence'], emb_dir)

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.

Starting subset: 8 current time: 36374.7127468586s
De 0 a 96
De 96 a 192
De 192 a 288
De 288 a 384
De 384 a 480
De 480 a 576
De 576 a 672
De 672 a 768
De 768 a 864
De 864 a 960
De 960 a 1056
De 1056 a 1152
De 1152 a 1248
De 1248 a 1344
De 1344 a 1440
De 1440 a 1536
De 1536 a 1632
De 1632 a 1728
De 1728 a 1824
De 1824 a 1920
De 1920 a 2016
De 2016 a 2112
De 2112 a 2208
De 2208 a 2304
De 2304 a 2400
De 2400 a 2496
De 2496 a 2592
De 2592 a 2688
De 2688 a 2784
De 2784 a 2880
De 2880 a 2976
De 2976 a 3072
De 3072 a 3168
De 3168 a 3264
De 3264 a 3360
De 3360 a 3456
De 3456 a 3552
De 3552 a 3648
De 3648 a 3744
De 3744 a 3840
De 3840 a 3936
De 3936 a 4032
De 4032 a 4128
De 4128 a 4224
De 4224 a 4320
De 4320 a 4416
De 4416 a 4512
De 4512 a 4608
De 4608 a 4704
De 4704 a 4800
De 4800 a 4896
De 4896 a 4992
De 4992 a 5088
De 5088 a 5184
De 5184 a 5280
De 5280 a 5376
De 5376 a 5472
De 5472 a 5568
De 5568 a 5664
De 5664 a 5760
De 5760 a 5856
De 5856 a 5952
De 5952 a 6048
De 6048 a 6144
De 6144 a 6240
De 6240 a 6336
De 6336 a 6432
De 6432 a 6528
De 6528 a 6624
De 6624 a 6720
De 6720 a 6816
De 6816 a 6912
De 6912 a 7008
De 7008 a 7104
De 7104 a 7200
De 7200 a 7296
De 7296 a 7392
De 7392 a 7488
De 7488 a 7584
De 7584 a 7680
De 7680 a 7776
De 7776 a 7872
De 7872 a 7968
De 7968 a 8064
De 8064 a 8160
De 8160 a 8256
De 8256 a 8352
De 8352 a 8448
De 8448 a 8544
De 8544 a 8640
De 8640 a 8736
De 8736 a 8832
De 8832 a 8928
De 8928 a 9024
De 9024 a 9120
De 9120 a 9216
De 9216 a 9312
De 9312 a 9408
De 9408 a 9504
De 9504 a 9600
De 9600 a 9696
De 9696 a 9792
De 9792 a 9888
De 9888 a 9984
De 9984 a 10080
De 10080 a 10176
De 10176 a 10272
De 10272 a 10368
De 10368 a 10464
De 10464 a 10560
De 10560 a 10656
De 10656 a 10752
De 10752 a 10848
De 10848 a 10944
De 10944 a 11040
De 11040 a 11136
De 11136 a 11232
De 11232 a 11328
De 11328 a 11424
De 11424 a 11520
De 11520 a 11616
De 11616 a 11712
De 11712 a 11808
De 11808 a 11904
De 11904 a 12000
De 12000 a 12096
De 12096 a 12192
De 12192 a 12288
De 12288 a 12384
De 12384 a 12480
De 12480 a 12576
De 12576 a 12672
De 12672 a 12768
De 12768 a 12864
De 12864 a 12960
De 12960 a 13056
De 13056 a 13152
De 13152 a 13248
De 13248 a 13344
De 13344 a 13440
De 13440 a 13536
De 13536 a 13632
De 13632 a 13728
De 13728 a 13824
De 13824 a 13920
De 13920 a 14016
De 14016 a 14112
De 14112 a 14208
De 14208 a 14304
De 14304 a 14400
De 14400 a 14496
De 14496 a 14592
De 14592 a 14688
De 14688 a 14784
De 14784 a 14880
De 14880 a 14976
De 14976 a 15072
De 15072 a 15168
De 15168 a 15264
De 15264 a 15360
De 15360 a 15456
De 15456 a 15552
De 15552 a 15648
De 15648 a 15744
De 15744 a 15840
De 15840 a 15936
De 15936 a 16032
De 16032 a 16128
De 16128 a 16224
De 16224 a 16320
De 16320 a 16416
De 16416 a 16512
De 16512 a 16608
De 16608 a 16704
De 16704 a 16800
De 16800 a 16896
De 16896 a 16992
De 16992 a 17088
De 17088 a 17184
De 17184 a 17280
De 17280 a 17376
De 17376 a 17472
De 17472 a 17568
De 17568 a 17664
De 17664 a 17760
De 17760 a 17856
De 17856 a 17952
De 17952 a 18048
De 18048 a 18144
De 18144 a 18240
De 18240 a 18336
De 18336 a 18432
De 18432 a 18528
De 18528 a 18624
De 18624 a 18720
De 18720 a 18816
De 18816 a 18912
De 18912 a 19008
De 19008 a 19104
De 19104 a 19200
De 19200 a 19296
De 19296 a 19392
De 19392 a 19488
De 19488 a 19584
De 19584 a 19680
De 19680 a 19776
De 19776 a 19872
De 19872 a 19968
De 19968 a 20064
De 20064 a 20160
De 20160 a 20256
De 20256 a 20352
De 20352 a 20448
De 20448 a 20544
De 20544 a 20640
De 20640 a 20736
De 20736 a 20832
De 20832 a 20928
De 20928 a 21024
De 21024 a 21120
De 21120 a 21216
De 21216 a 21312
De 21312 a 21408
De 21408 a 21504
De 21504 a 21600
De 21600 a 21696
De 21696 a 21792
De 21792 a 21888
De 21888 a 21984
De 21984 a 22080
De 22080 a 22176
De 22176 a 22272
De 22272 a 22368
De 22368 a 22464
De 22464 a 22560
De 22560 a 22656
De 22656 a 22752
De 22752 a 22848
De 22848 a 22944
De 22944 a 23040
De 23040 a 23136
De 23136 a 23232
De 23232 a 23328
De 23328 a 23424
De 23424 a 23520
De 23520 a 23616
De 23616 a 23712
De 23712 a 23808
De 23808 a 23904
De 23904 a 24000
De 24000 a 24096
De 24096 a 24192
De 24192 a 24288
De 24288 a 24384
De 24384 a 24480
De 24480 a 24576
De 24576 a 24672
De 24672 a 24768
De 24768 a 24864
De 24864 a 24960
De 24960 a 25056
De 25056 a 25152
De 25152 a 25248
De 25248 a 25344
De 25344 a 25440
De 25440 a 25536
De 25536 a 25632
De 25632 a 25728
De 25728 a 25824
De 25824 a 25920
De 25920 a 26016
De 26016 a 26112
De 26112 a 26208
De 26208 a 26304
De 26304 a 26400
De 26400 a 26496
De 26496 a 26592
De 26592 a 26688
De 26688 a 26784
De 26784 a 26880
De 26880 a 26976
De 26976 a 27072
De 27072 a 27168
De 27168 a 27264
De 27264 a 27360
De 27360 a 27456
De 27456 a 27552
De 27552 a 27648
De 27648 a 27744
De 27744 a 27840
De 27840 a 27936
De 27936 a 28032
De 28032 a 28128
De 28128 a 28224
De 28224 a 28320
De 28320 a 28416
De 28416 a 28512
De 28512 a 28608
De 28608 a 28704
De 28704 a 28800
De 28800 a 28896
De 28896 a 28992
De 28992 a 29088
De 29088 a 29184
De 29184 a 29280
De 29280 a 29376
De 29376 a 29472
De 29472 a 29568
De 29568 a 29664
De 29664 a 29760
De 29760 a 29856
De 29856 a 29952
De 29952 a 30048
De 30048 a 30144
De 30144 a 30240
De 30240 a 30336
De 30336 a 30432
De 30432 a 30528
De 30528 a 30624
De 30624 a 30720
De 30720 a 30816
De 30816 a 30912
De 30912 a 31008
De 31008 a 31104
De 31104 a 31200
De 31200 a 31296
De 31296 a 31392
De 31392 a 31488
De 31488 a 31584
De 31584 a 31680
De 31680 a 31776
De 31776 a 31872
De 31872 a 31968
De 31968 a 32064
De 32064 a 32160
De 32160 a 32256
De 32256 a 32352
De 32352 a 32448
De 32448 a 32544
De 32544 a 32640
De 32640 a 32736
De 32736 a 32832
De 32832 a 32928
De 32928 a 33024
De 33024 a 33120
De 33120 a 33216
De 33216 a 33312
De 33312 a 33408
De 33408 a 33504
De 33504 a 33600
De 33600 a 33696
De 33696 a 33792
De 33792 a 33888
De 33888 a 33984
De 33984 a 34080
De 34080 a 34176
De 34176 a 34272
De 34272 a 34368
De 34368 a 34464
De 34464 a 34560
De 34560 a 34656
De 34656 a 34752
De 34752 a 34848
De 34848 a 34944
De 34944 a 35040
De 35040 a 35136
De 35136 a 35232
De 35232 a 35328
De 35328 a 35424
De 35424 a 35520
De 35520 a 35616
De 35616 a 35712
De 35712 a 35808
De 35808 a 35904
De 35904 a 36000
De 36000 a 36096
De 36096 a 36192
De 36192 a 36288
De 36288 a 36384
De 36384 a 36480
De 36480 a 36576
De 36576 a 36672
De 36672 a 36768
De 36768 a 36864
De 36864 a 36960
De 36960 a 37056
De 37056 a 37152
De 37152 a 37248
De 37248 a 37344
De 37344 a 37440
De 37440 a 37536
De 37536 a 37632
De 37632 a 37728
De 37728 a 37824
De 37824 a 37920
De 37920 a 38016
De 38016 a 38112
De 38112 a 38208
De 38208 a 38304
De 38304 a 38400
De 38400 a 38496
De 38496 a 38592
De 38592 a 38688
De 38688 a 38784
De 38784 a 38880
De 38880 a 38976
De 38976 a 39072
De 39072 a 39168
De 39168 a 39264
De 39264 a 39360
De 39360 a 39456
De 39456 a 39552
De 39552 a 39648
De 39648 a 39744
De 39744 a 39840
De 39840 a 39936

In [ ]:
generate_embeddings(df_valid['processed_sequence'], valid_emb_dir)

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.

Starting subset: 0 current time: 0.0s
De 0 a 96
De 96 a 192
De 192 a 288
De 288 a 384
De 384 a 480
De 480 a 576
De 576 a 672
De 672 a 768
De 768 a 864
De 864 a 960
De 960 a 1056
De 1056 a 1152
De 1152 a 1248
De 1248 a 1344
De 1344 a 1440
De 1440 a 1536
De 1536 a 1632
De 1632 a 1728
De 1728 a 1824
De 1824 a 1920
De 1920 a 2016
De 2016 a 2112
De 2112 a 2208
De 2208 a 2304
De 2304 a 2400
De 2400 a 2496
De 2496 a 2592
De 2592 a 2688
De 2688 a 2784
De 2784 a 2880
De 2880 a 2976
De 2976 a 3072
De 3072 a 3168
De 3168 a 3264
De 3264 a 3360
De 3360 a 3456
De 3456 a 3552
De 3552 a 3648
De 3648 a 3744
De 3744 a 3840
De 3840 a 3936
De 3936 a 4032
De 4032 a 4128
De 4128 a 4224
De 4224 a 4320
De 4320 a 4416
De 4416 a 4512
De 4512 a 4608
De 4608 a 4704
De 4704 a 4800
De 4800 a 4896
De 4896 a 4992
De 4992 a 5088
De 5088 a 5184
De 5184 a 5280
De 5280 a 5376
De 5376 a 5472
De 5472 a 5568
De 5568 a 5664
De 5664 a 5760
De 5760 a 5856
De 5856 a 5952
De 5952 a 6048
De 6048 a 6144
De 6144 a 6240
De 6240 a 6336
De 6336 a 6432
De 6432 a 6528
De 6528 a 6624
De 6624 a 6720
De 6720 a 6816
De 6816 a 6912
De 6912 a 7008
De 7008 a 7104
De 7104 a 7200
De 7200 a 7296
De 7296 a 7392
De 7392 a 7488
De 7488 a 7584
De 7584 a 7680
De 7680 a 7776
De 7776 a 7872
De 7872 a 7968
De 7968 a 8064
De 8064 a 8160
De 8160 a 8256
De 8256 a 8352
De 8352 a 8448
De 8448 a 8544
De 8544 a 8640
De 8640 a 8736
De 8736 a 8832
De 8832 a 8928
De 8928 a 9024
De 9024 a 9120
De 9120 a 9216
De 9216 a 9312
De 9312 a 9408
De 9408 a 9504
De 9504 a 9600
De 9600 a 9696
De 9696 a 9792
De 9792 a 9888
De 9888 a 9984
De 9984 a 10080
De 10080 a 10176
De 10176 a 10272
De 10272 a 10368
De 10368 a 10464
De 10464 a 10560
De 10560 a 10656
De 10656 a 10752
De 10752 a 10848
De 10848 a 10944
De 10944 a 11040
De 11040 a 11136
De 11136 a 11232
De 11232 a 11328
De 11328 a 11424
De 11424 a 11520
De 11520 a 11616
De 11616 a 11712
De 11712 a 11808
De 11808 a 11904
De 11904 a 12000
De 12000 a 12096
De 12096 a 12192
De 12192 a 12288
De 12288 a 12384
De 12384 a 12480
De 12480 a 12576
De 12576 a 12672
De 12672 a 12768
De 12768 a 12864
De 12864 a 12960
De 12960 a 13056
De 13056 a 13152
De 13152 a 13248
De 13248 a 13344
De 13344 a 13440
De 13440 a 13536
De 13536 a 13632
De 13632 a 13728
De 13728 a 13824
De 13824 a 13920
De 13920 a 14016
De 14016 a 14112
De 14112 a 14208
De 14208 a 14304
De 14304 a 14400
De 14400 a 14496
De 14496 a 14592
De 14592 a 14688
De 14688 a 14784
De 14784 a 14880
De 14880 a 14976
De 14976 a 15072
De 15072 a 15168
De 15168 a 15264
De 15264 a 15360
De 15360 a 15456
De 15456 a 15552
De 15552 a 15648
De 15648 a 15744
De 15744 a 15840
De 15840 a 15936
De 15936 a 16032
De 16032 a 16128
De 16128 a 16224
De 16224 a 16320
De 16320 a 16416
De 16416 a 16512
De 16512 a 16608
De 16608 a 16704
De 16704 a 16800
De 16800 a 16896
De 16896 a 16992
De 16992 a 17088
De 17088 a 17184
De 17184 a 17280
De 17280 a 17376
De 17376 a 17472
De 17472 a 17568
De 17568 a 17664
De 17664 a 17760
De 17760 a 17856
De 17856 a 17952
De 17952 a 18048
De 18048 a 18144
De 18144 a 18240
De 18240 a 18336
De 18336 a 18432
De 18432 a 18528
De 18528 a 18624
De 18624 a 18720
De 18720 a 18816
De 18816 a 18912
De 18912 a 19008
De 19008 a 19104
De 19104 a 19200
De 19200 a 19296
De 19296 a 19392
De 19392 a 19488
De 19488 a 19584
De 19584 a 19680
De 19680 a 19776
De 19776 a 19872
De 19872 a 19968
De 19968 a 20064
De 20064 a 20160
De 20160 a 20256
De 20256 a 20352
De 20352 a 20448
De 20448 a 20544
De 20544 a 20640
De 20640 a 20736
De 20736 a 20832
De 20832 a 20928
De 20928 a 21024
De 21024 a 21120
De 21120 a 21216
De 21216 a 21312
De 21312 a 21408
De 21408 a 21504
De 21504 a 21600
De 21600 a 21696
De 21696 a 21792
De 21792 a 21888
De 21888 a 21984
De 21984 a 22047
Saved, current time: 3587.6290805339813s

In [ ]:
generate_embeddings(df_test['processed_sequence'], test_emb_dir)

Starting subset: 0 current time: 0.0s
De 0 a 96
De 96 a 192
De 192 a 288
De 288 a 384
De 384 a 480
De 480 a 576
De 576 a 672
De 672 a 768
De 768 a 864
De 864 a 960
De 960 a 1056
De 1056 a 1152
De 1152 a 1248
De 1248 a 1344
De 1344 a 1440
De 1440 a 1536
De 1536 a 1632
De 1632 a 1728
De 1728 a 1824
De 1824 a 1920
De 1920 a 2016
De 2016 a 2112
De 2112 a 2208
De 2208 a 2304
De 2304 a 2400
De 2400 a 2496
De 2496 a 2592
De 2592 a 2688
De 2688 a 2784
De 2784 a 2880
De 2880 a 2976
De 2976 a 3072
De 3072 a 3168
De 3168 a 3264
De 3264 a 3360
De 3360 a 3456
De 3456 a 3552
De 3552 a 3648
De 3648 a 3744
De 3744 a 3840
De 3840 a 3936
De 3936 a 4032
De 4032 a 4128
De 4128 a 4224
De 4224 a 4320
De 4320 a 4416
De 4416 a 4512
De 4512 a 4608
De 4608 a 4704
De 4704 a 4800
De 4800 a 4896
De 4896 a 4992
De 4992 a 5088
De 5088 a 5184
De 5184 a 5280
De 5280 a 5376
De 5376 a 5472
De 5472 a 5568
De 5568 a 5664
De 5664 a 5760
De 5760 a 5856
De 5856 a 5952
De 5952 a 6048
De 6048 a 6144
De 6144 a 6240
De 6240 a 6336
De 6336 a 6432
De 6432 a 6528
De 6528 a 6624
De 6624 a 6720
De 6720 a 6816
De 6816 a 6912
De 6912 a 7008
De 7008 a 7104
De 7104 a 7200
De 7200 a 7296
De 7296 a 7392
De 7392 a 7488
De 7488 a 7584
De 7584 a 7680
De 7680 a 7776
De 7776 a 7872
De 7872 a 7968
De 7968 a 8064
De 8064 a 8160
De 8160 a 8256
De 8256 a 8352
De 8352 a 8448
De 8448 a 8544
De 8544 a 8640
De 8640 a 8736
De 8736 a 8832
De 8832 a 8928
De 8928 a 9024
De 9024 a 9120
De 9120 a 9216
De 9216 a 9312
De 9312 a 9408
De 9408 a 9504
De 9504 a 9600
De 9600 a 9696
De 9696 a 9792
De 9792 a 9888
De 9888 a 9984
De 9984 a 10080
De 10080 a 10176
De 10176 a 10272
De 10272 a 10368
De 10368 a 10464
De 10464 a 10560
De 10560 a 10656
De 10656 a 10752
De 10752 a 10848
De 10848 a 10944
De 10944 a 11040
De 11040 a 11136
De 11136 a 11232
De 11232 a 11328
De 11328 a 11424
De 11424 a 11520
De 11520 a 11616
De 11616 a 11712
De 11712 a 11808
De 11808 a 11904
De 11904 a 12000
De 12000 a 12096
De 12096 a 12192
De 12192 a 12288
De 12288 a 12384
De 12384 a 12480
De 12480 a 12576
De 12576 a 12672
De 12672 a 12768
De 12768 a 12864
De 12864 a 12960
De 12960 a 13056
De 13056 a 13152
De 13152 a 13248
De 13248 a 13344
De 13344 a 13440
De 13440 a 13536
De 13536 a 13632
De 13632 a 13728
De 13728 a 13824
De 13824 a 13920
De 13920 a 14016
De 14016 a 14112
De 14112 a 14208
De 14208 a 14304
De 14304 a 14400
De 14400 a 14496
De 14496 a 14592
De 14592 a 14688
De 14688 a 14784
De 14784 a 14880
De 14880 a 14976
De 14976 a 15072
De 15072 a 15168
De 15168 a 15264
De 15264 a 15360
De 15360 a 15456
De 15456 a 15552
De 15552 a 15648
De 15648 a 15744
De 15744 a 15840
De 15840 a 15936
De 15936 a 16032
De 16032 a 16128
De 16128 a 16224
De 16224 a 16320
De 16320 a 16416
De 16416 a 16512
De 16512 a 16608
De 16608 a 16704
De 16704 a 16800
De 16800 a 16896
De 16896 a 16992
De 16992 a 17088
De 17088 a 17184
De 17184 a 17280
De 17280 a 17376
De 17376 a 17472
De 17472 a 17568
De 17568 a 17664
De 17664 a 17760
De 17760 a 17856
De 17856 a 17952
De 17952 a 18048
De 18048 a 18144
De 18144 a 18240
De 18240 a 18336
De 18336 a 18432
De 18432 a 18528
De 18528 a 18624
De 18624 a 18720
De 18720 a 18816
De 18816 a 18912
De 18912 a 19008
De 19008 a 19104
De 19104 a 19200
De 19200 a 19296
De 19296 a 19392
De 19392 a 19488
De 19488 a 19584
De 19584 a 19680
De 19680 a 19776
De 19776 a 19872
De 19872 a 19968
De 19968 a 20064
De 20064 a 20160
De 20160 a 20256
De 20256 a 20352
De 20352 a 20448
De 20448 a 20544
De 20544 a 20640
De 20640 a 20736
De 20736 a 20832
De 20832 a 20928
De 20928 a 21024
De 21024 a 21120
De 21120 a 21216
De 21216 a 21312
De 21312 a 21408
De 21408 a 21504
De 21504 a 21600
De 21600 a 21696
De 21696 a 21792
De 21792 a 21888
De 21888 a 21984
De 21984 a 22046
Saved, current time: 3593.419534921646s

In [12]:
generate_embeddings(df_g18_19['processed_sequence'], g18_19_emb_dir)

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.

Starting subset: 0 current time: 0.0s
De 0 a 96
De 96 a 192
De 192 a 288
De 288 a 384
De 384 a 459
Saved, current time: 75.42132997512817s

In [19]:
embs_train = np.array([])
for i in range((len(df_train) // 40000) + 1):
  subset = np.load(os.path.join(emb_dir, f'subset_{i}.npy'))
  if len(embs_train) == 0:
    embs_train = subset
  else:
    embs_train = np.vstack((embs_train, subset))

In [ ]:
np.save(str(current_dir / 'datasets/First Level/train_embeddings.npy'), embs_train)

In [ ]:
valid_embeddings = np.load(str(current_dir / 'datasets/Validation/valid_embeddings/subset_0.npy'))
np.save(str(current_dir / 'datasets/First Level/valid_embeddings.npy'), valid_embeddings)
test_embeddings = np.load(str(current_dir / 'datasets/Test/test_embeddings/subset_0.npy'))
np.save(str(current_dir / 'datasets/First Level/test_embeddings.npy'), test_embeddings)

In [ ]:
g18_g19_embeddings = np.load(str(current_dir / 'datasets/G18_G19_Embeddings/subset_0.npy'))

In [ ]:
np.save(str(current_dir / 'datasets/GH18_Gh19_embeddings.npy'), g18_g19_embeddings)